Fix Bug 1180173
yast/yast-update-alternatives pull request #51
Opened 2020-12-17 15:08 UTC by KaratekHD

This should fix https://bugzilla.opensuse.org/show_bug.cgi?id=1180173

2020-12-17 15:13 UTC, imobachgs requested changes
Thanks for the patch. I will backport this change to `SLE-15-SP2` once it is merged.

2020-12-17 15:13 UTC, imobachgs commented on package/yast2-alternatives.changes
> +- Change .desktop file so module launches with xdg-su
Please, add the bug number.

```
 - Change .desktop file so module launches with xdg-su (bsc#1180173).
```

2020-12-17 18:05 UTC, KaratekHD commented on package/yast2-alternatives.changes
> +- Change .desktop file so module launches with xdg-su
Done

2020-12-18 11:26 UTC, imobachgs approved these changes
Thanks a lot! I will merge the code and close the bug.

2020-12-18 11:26 UTC, merged